import Button from '@app/components/Common/Button';
import LoadingSpinner from '@app/components/Common/LoadingSpinner';
import Modal from '@app/components/Common/Modal';
import SensitiveInput from '@app/components/Common/SensitiveInput';
import CandidateDiagnostics from '@app/components/Settings/SettingsFresh/CandidateDiagnostics';
import FreshContentFilters from '@app/components/Settings/SettingsFresh/FreshContentFilters';
import {
  loadFreshFilters,
  selectedFreshFilter,
  toFreshConnectionUpdate,
  toFreshFilterSelectOptions,
  toFreshSettingsFormValues,
  toFreshSettingsUpdate,
  type FreshFilterOption,
  type FreshSettingsResponse,
} from '@app/components/Settings/SettingsFresh/settingsFresh';
import useToasts from '@app/hooks/useToasts';
import defineMessages from '@app/utils/defineMessages';
import { Transition } from '@headlessui/react';
import { ArrowPathIcon, BeakerIcon } from '@heroicons/react/24/solid';
import type { FreshDiagnosticsSnapshot } from '@server/lib/fresh';
import axios from 'axios';
import { Field, Form, Formik } from 'formik';
import { Fragment, useEffect, useState } from 'react';
import { useIntl } from 'react-intl';
import Select from 'react-select';
import useSWR, { mutate } from 'swr';
import * as Yup from 'yup';

interface DiagnosticsResponse {
  latestAttempt: FreshDiagnosticsSnapshot | null;
  currentProjection: {
    status: string;
    refreshing: boolean;
    lastRefresh?: string;
    lastReconciliation?: string;
    checkpoint?: string;
    continuityStatus?: number;
    itemCount: number;
    error?: string;
  };
}
const messages = defineMessages('components.Settings.SettingsFresh', {
  title: 'Fresh',
  description:
    'Configure autobrr-backed Fresh discovery and inspect synchronization diagnostics.',
  enabled: 'Enable Fresh',
  hostname: 'Hostname or IP Address',
  port: 'Port',
  ssl: 'Use SSL',
  apiToken: 'API Token',
  apiTokenHelp: 'Enter the API token generated by autobrr.',
  filter: 'autobrr Filter',
  filterHelp:
    'Use a dedicated non-acquiring autobrr filter that represents the broad release-quality envelope you care about. autobrr determines release viability; Seerr determines recent-media relevance; Radarr and Sonarr remain authoritative for acquisition.',
  loadingFilter: 'Loading configured filter…',
  unavailableFilter: 'Configured filter unavailable (ID: {id})',
  mediaEligibilityDays: 'Media eligibility window (days)',
  mediaEligibilityHelp:
    'At the first qualifying observation, how old the canonical movie release or series first-air date may be.',
  freshVisibilityDays: 'Keep items in Fresh for (days)',
  freshVisibilityHelp:
    'How long admitted media remains visible after its first qualifying observation.',
  test: 'Test Connection & Load Filters',
  save: 'Save Changes',
  saved: 'Fresh settings saved.',
  saveFailed: 'Fresh settings could not be saved.',
  testSuccess: 'Connected to autobrr and loaded filters.',
  testFailed: 'Unable to connect to autobrr.',
  diagnostics: 'Fresh Pipeline',
  refresh: 'Sync Now',
  refreshSuccess: 'Fresh synchronization completed.',
  refreshFailed:
    'Fresh refresh failed. The last-good projection remains available.',
  refreshFailedNoProjection:
    'Fresh synchronization failed. No successful Fresh dataset is currently available.',
  refreshDisabled: 'Enable and save Fresh settings before refreshing.',
  maintenance: 'Maintenance',
  maintenanceHelp:
    'Rebuild persistent Fresh discovery data only when a clean source reconstruction is required.',
  rebuild: 'Rebuild Fresh Data',
  rebuildTitle: 'Rebuild Fresh Data?',
  rebuildConfirm:
    'This deletes all persisted Fresh discovery history and rebuilds it from releases currently retained by autobrr. Fresh observations no longer present in autobrr Release History cannot be recovered. Watchlist, requests, media-library state, Radarr, Sonarr, and autobrr are unaffected.',
  rebuildSuccess: 'Fresh data was rebuilt successfully.',
  rebuildFailed:
    'Fresh data could not be rebuilt. Check the pipeline status for the failed stage.',
  latestAttempt: 'Latest refresh attempt',
  currentProjection: 'Current last-good projection',
  currentItems: 'Current Fresh items',
  checkpoint: 'Source checkpoint',
  continuity: 'Continuity',
  lastSuccessfulSync: 'Last successful sync',
  lastSuccessfulReconciliation: 'Last successful reconciliation',
  currentState: 'Current state',
  uninitialized: 'Uninitialized',
  current: 'Current',
  reconciliationRequired: 'Reconciliation required',
  gapPreserved: 'Gap preserved',
  stages: 'Stages',
  failedAt: 'Failed at {stage}: {reason}',
  retainedProjection:
    'Current Fresh dataset retained from {timestamp} ({count} items).',
  noProjection: 'No successful Fresh dataset is currently available.',
  noDiagnostics: 'No completed Fresh refresh has diagnostics yet.',
  decisions: 'Recent decisions',
  newReleases: 'New autobrr releases',
  persisted: 'Persisted observations',
  replayed: 'Duplicate/replayed observations',
  candidates: 'Unique candidate identities',
  alreadyResolved: 'Already resolved',
  attempts: 'Resolution attempts',
  resolved: 'Resolved',
  noMatch: 'No match',
  ambiguous: 'Ambiguous',
  transient: 'Transient failures',
  outsideWindow: 'Outside eligibility window',
  newMedia: 'New Fresh media',
  updatedMedia: 'Existing Fresh media updated',
  expiredMedia: 'Expired Fresh media',
  currentMedia: 'Current Fresh media',
  outcome: 'Outcome',
  gate: 'Stage',
  reason: 'Reason',
  matched: 'Matched media',
  type: 'Type',
  year: 'Year',
  mediaTitle: 'Title',
});

const diagnosticLabels: Record<string, string> = {
  configuration: 'Configuration',
  filter_authentication: 'Filter Authentication',
  source_history: 'Release History',
  observation_persistence: 'Save Observations',
  checkpoint_commit: 'Save Checkpoint',
  resolution_search: 'TMDB Resolution',
  projection_update: 'Update Fresh Media',
  retention: 'Retention',
  reconciliation: 'Reconciliation',
  not_started: 'Not Started',
  running: 'Running',
  succeeded: 'Succeeded',
  failed: 'Failed',
  cancelled: 'Cancelled',
  invalid_configuration: 'Invalid Configuration',
  filter_missing: 'Configured Filter Missing',
  filter_disabled: 'Configured Filter Disabled',
  source_unavailable: 'autobrr Temporarily Unavailable',
  invalid_source_response: 'Invalid autobrr Response',
  invalid_source_order: 'Invalid Release History Order',
  checkpoint_missing: 'Source Checkpoint Missing',
  source_id_regression: 'Source Identity Regressed',
  tmdb_unavailable: 'TMDB Temporarily Unavailable',
  tmdb_rate_limited: 'TMDB Rate Limited',
  persistence_failed: 'Database Update Failed',
  unexpected_failure: 'Unexpected Failure',
  source_observation_persisted: 'Source Observation Saved',
  active_fresh: 'Active Fresh',
  outside_eligibility_window: 'Outside Eligibility Window',
  visibility_expired: 'Visibility Expired',
  excluded_genre: 'Excluded Genre',
  excluded_original_language: 'Excluded Original Language',
  excluded_content_rating: 'Excluded Content Rating',
  below_tmdb_score: 'Below Minimum TMDB Score',
  below_tmdb_vote_count: 'Below Minimum TMDB Votes',
};

const diagnosticLabel = (value: string) =>
  diagnosticLabels[value] ??
  value
    .replaceAll('_', ' ')
    .replace(/\b\w/g, (character) => character.toUpperCase());
const SettingsFresh = () => {
  const intl = useIntl();
  const { addToast } = useToasts();
  const [filters, setFilters] = useState<FreshFilterOption[]>([]);
  const [filtersLoaded, setFiltersLoaded] = useState(false);
  const [loadingFilters, setLoadingFilters] = useState(false);
  const [testing, setTesting] = useState(false);
  const [refreshing, setRefreshing] = useState(false);
  const [rebuilding, setRebuilding] = useState(false);
  const [showRebuildConfirmation, setShowRebuildConfirmation] = useState(false);
  const {
    data,
    error,
    mutate: revalidate,
  } = useSWR<FreshSettingsResponse>('/api/v1/settings/fresh');
  const { data: diagnostics, mutate: revalidateDiagnostics } =
    useSWR<DiagnosticsResponse>('/api/v1/settings/fresh/diagnostics');
  const apiTokenConfigured = data?.apiTokenConfigured;
  const baseUrl = data?.baseUrl;
  useEffect(() => {
    if (!apiTokenConfigured || !baseUrl) {
      setFiltersLoaded(true);
      return;
    }
    let active = true;
    setLoadingFilters(true);
    void axios
      .post<FreshFilterOption[]>('/api/v1/settings/fresh/filters', {})
      .then((response) => {
        if (active) setFilters(response.data);
      })
      .catch(() => undefined)
      .finally(() => {
        if (active) {
          setFiltersLoaded(true);
          setLoadingFilters(false);
        }
      });
    return () => {
      active = false;
    };
  }, [apiTokenConfigured, baseUrl]);
  if (!data && !error) return <LoadingSpinner />;
  if (!data) return null;
  const schema = Yup.object({
    enabled: Yup.boolean().required(),
    protocol: Yup.string().oneOf(['http', 'https']).required(),
    hostname: Yup.string()
      .max(253)
      .when('enabled', { is: true, then: (value) => value.required() }),
    port: Yup.number().integer().min(1).max(65535).required(),
    apiToken: Yup.string()
      .max(1024)
      .when('enabled', {
        is: true,
        then: (value) => (data.apiTokenConfigured ? value : value.required()),
      }),
    filterId: Yup.number()
      .integer()
      .when('enabled', {
        is: true,
        then: (value) => value.min(1),
        otherwise: (value) => value.min(0),
      })
      .required(),
    cachedFilterName: Yup.string().max(200),
    mediaEligibilityDays: Yup.number().integer().min(1).max(365).required(),
    freshVisibilityDays: Yup.number().integer().min(1).max(90).required(),
    includeGenreIds: Yup.array().of(Yup.number().integer().positive()),
    excludeGenreIds: Yup.array().of(Yup.number().integer().positive()),
    includeOriginalLanguages: Yup.array().of(Yup.string()),
    excludeOriginalLanguages: Yup.array().of(Yup.string()),
    includeContentRatings: Yup.array().of(Yup.string()),
    excludeContentRatings: Yup.array().of(Yup.string()),
    minimumTmdbScore: Yup.number().min(0).max(10).required(),
    minimumTmdbVotes: Yup.number().integer().min(0).max(10000000).required(),
  });
  const counts = diagnostics?.latestAttempt?.counts;
  const projection = diagnostics?.currentProjection;
  const formatTimestamp = (value?: string) =>
    value
      ? intl.formatDate(new Date(value), {
          dateStyle: 'medium',
          timeStyle: 'short',
        })
      : '—';
  const continuity = projection?.continuityStatus
    ? intl.formatMessage(
        projection.continuityStatus === 1
          ? messages.uninitialized
          : projection.continuityStatus === 2
            ? messages.current
            : projection.continuityStatus === 3
              ? messages.reconciliationRequired
              : messages.gapPreserved
      )
    : '—';
  const projectionRows = [
    [messages.currentItems, projection?.itemCount?.toLocaleString() ?? '—'],
    [messages.checkpoint, projection?.checkpoint ?? '—'],
    [messages.continuity, continuity],
    [messages.lastSuccessfulSync, formatTimestamp(projection?.lastRefresh)],
    [
      messages.lastSuccessfulReconciliation,
      formatTimestamp(projection?.lastReconciliation),
    ],
    [
      messages.currentState,
      projection
        ? `${projection.status}${projection.refreshing ? ' (running)' : ''}`
        : '—',
    ],
  ] as const;
  const countRows = counts
    ? ([
        [messages.newReleases, counts.newAutobrrReleases],
        [messages.persisted, counts.persistedObservations],
        [messages.replayed, counts.replayedObservations],
        [messages.candidates, counts.uniqueCandidates],
        [messages.alreadyResolved, counts.alreadyResolved],
        [messages.attempts, counts.resolutionAttempts],
        [messages.resolved, counts.resolved],
        [messages.noMatch, counts.noMatch],
        [messages.ambiguous, counts.ambiguous],
        [messages.transient, counts.transientFailures],
        [messages.outsideWindow, counts.outsideFreshWindow],
        [messages.newMedia, counts.newFreshMedia],
        [messages.updatedMedia, counts.existingFreshMediaUpdated],
        [messages.expiredMedia, counts.expiredFreshMedia],
        [messages.currentMedia, counts.currentFreshMedia],
      ] as const)
    : [];
  const rebuildFresh = async () => {
    setShowRebuildConfirmation(false);
    setRebuilding(true);
    try {
      await axios.post('/api/v1/settings/fresh/rebuild');
      await Promise.all([revalidateDiagnostics(), mutate('/api/v1/fresh')]);
      addToast(intl.formatMessage(messages.rebuildSuccess), {
        appearance: 'success',
        autoDismiss: true,
      });
    } catch {
      await revalidateDiagnostics();
      addToast(intl.formatMessage(messages.rebuildFailed), {
        appearance: 'error',
        autoDismiss: true,
      });
    } finally {
      setRebuilding(false);
    }
  };
  return (
    <>
      <Transition
        as={Fragment}
        show={showRebuildConfirmation}
        enter="transition-opacity ease-in-out duration-300"
        enterFrom="opacity-0"
        enterTo="opacity-100"
        leave="transition-opacity ease-in-out duration-300"
        leaveFrom="opacity-100"
        leaveTo="opacity-0"
      >
        <Modal
          title={intl.formatMessage(messages.rebuildTitle)}
          okText={intl.formatMessage(messages.rebuild)}
          okButtonType="danger"
          onOk={rebuildFresh}
          onCancel={() => setShowRebuildConfirmation(false)}
        >
          {intl.formatMessage(messages.rebuildConfirm)}
        </Modal>
      </Transition>
      <div className="mb-6">
        <h3 className="heading">{intl.formatMessage(messages.title)}</h3>
        <p className="description">
          {intl.formatMessage(messages.description)}
        </p>
      </div>
      <Formik
        enableReinitialize
        validationSchema={schema}
        initialValues={toFreshSettingsFormValues(data)}
        onSubmit={async (values) => {
          try {
            await axios.put(
              '/api/v1/settings/fresh',
              toFreshSettingsUpdate(values)
            );
            await Promise.all([
              revalidate(),
              mutate('/api/v1/settings/public'),
            ]);
            addToast(intl.formatMessage(messages.saved), {
              appearance: 'success',
              autoDismiss: true,
            });
          } catch {
            addToast(intl.formatMessage(messages.saveFailed), {
              appearance: 'error',
              autoDismiss: true,
            });
          }
        }}
      >
        {({
          values,
          setFieldValue,
          isSubmitting,
          isValid,
          errors,
          touched,
        }) => {
          const loadFilters = async () => {
            setTesting(true);
            const result = await loadFreshFilters(async () => {
              const response = await axios.post<FreshFilterOption[]>(
                '/api/v1/settings/fresh/filters',
                toFreshConnectionUpdate(values)
              );
              return response.data;
            });
            if (result.ok) {
              setFilters(result.filters);
              setFiltersLoaded(true);
              addToast(intl.formatMessage(messages.testSuccess), {
                appearance: 'success',
                autoDismiss: true,
              });
            } else {
              addToast(intl.formatMessage(messages.testFailed), {
                appearance: 'error',
                autoDismiss: true,
              });
            }
            setTesting(false);
          };
          const filterOptions = toFreshFilterSelectOptions(filters);
          return (
            <Form className="section">
              <div className="form-row">
                <label className="checkbox-label" htmlFor="enabled">
                  {intl.formatMessage(messages.enabled)}
                </label>
                <div className="form-input-area">
                  <Field type="checkbox" id="enabled" name="enabled" />
                </div>
              </div>
              <div className="form-row">
                <label htmlFor="hostname" className="text-label">
                  {intl.formatMessage(messages.hostname)}
                  <span className="label-required">*</span>
                </label>
                <div className="form-input-area">
                  <div className="form-input-field">
                    <span className="inline-flex cursor-default items-center rounded-l-md border border-r-0 border-gray-500 bg-gray-800 px-3 text-gray-100 sm:text-sm">
                      {values.protocol}://
                    </span>
                    <Field
                      id="hostname"
                      name="hostname"
                      type="text"
                      inputMode="url"
                      className="rounded-r-only"
                    />
                  </div>
                  {errors.hostname && touched.hostname && (
                    <div className="error">{errors.hostname}</div>
                  )}
                </div>
              </div>
              <div className="form-row">
                <label htmlFor="port" className="text-label">
                  {intl.formatMessage(messages.port)}
                  <span className="label-required">*</span>
                </label>
                <div className="form-input-area">
                  <Field
                    id="port"
                    name="port"
                    type="text"
                    inputMode="numeric"
                    className="short"
                  />
                  {errors.port && touched.port && (
                    <div className="error">{errors.port}</div>
                  )}
                </div>
              </div>
              <div className="form-row">
                <label htmlFor="ssl" className="checkbox-label">
                  {intl.formatMessage(messages.ssl)}
                </label>
                <div className="form-input-area">
                  <Field
                    type="checkbox"
                    id="ssl"
                    name="ssl"
                    checked={values.protocol === 'https'}
                    onChange={() =>
                      setFieldValue(
                        'protocol',
                        values.protocol === 'https' ? 'http' : 'https'
                      )
                    }
                  />
                </div>
              </div>
              <div className="form-row">
                <label htmlFor="apiToken" className="text-label">
                  {intl.formatMessage(messages.apiToken)}
                  <span className="label-required">*</span>
                  <span className="label-tip">
                    {intl.formatMessage(messages.apiTokenHelp)}
                  </span>
                </label>
                <div className="form-input-area">
                  <div className="form-input-field">
                    <SensitiveInput
                      as="field"
                      id="apiToken"
                      name="apiToken"
                      onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
                        setFieldValue('apiToken', e.target.value)
                      }
                    />
                  </div>
                  {errors.apiToken &&
                    touched.apiToken &&
                    typeof errors.apiToken === 'string' && (
                      <div className="error">{errors.apiToken}</div>
                    )}
                </div>
              </div>
              <div className="form-row">
                <div />
                <div className="form-input-area">
                  <Button
                    type="button"
                    onClick={loadFilters}
                    disabled={testing || loadingFilters || isSubmitting}
                  >
                    {testing ? (
                      <ArrowPathIcon className="animate-spin" />
                    ) : (
                      <BeakerIcon />
                    )}
                    <span>{intl.formatMessage(messages.test)}</span>
                  </Button>
                </div>
              </div>
              <div className="form-row">
                <label htmlFor="filterId" className="text-label">
                  {intl.formatMessage(messages.filter)}
                  <span className="label-required">*</span>
                  <span className="label-tip">
                    {intl.formatMessage(messages.filterHelp)}
                  </span>
                </label>
                <div className="form-input-area">
                  <Select
                    inputId="filterId"
                    className="react-select-container"
                    classNamePrefix="react-select"
                    options={filterOptions}
                    value={selectedFreshFilter(
                      filterOptions,
                      Number(values.filterId),
                      filtersLoaded
                        ? values.cachedFilterName
                          ? `${values.cachedFilterName} (unverified)`
                          : intl.formatMessage(messages.unavailableFilter, {
                              id: values.filterId,
                            })
                        : intl.formatMessage(messages.loadingFilter)
                    )}
                    isLoading={testing || loadingFilters}
                    isDisabled={testing || loadingFilters || isSubmitting}
                    onChange={(option) => {
                      setFieldValue('filterId', option?.value ?? 0);
                      setFieldValue('cachedFilterName', option?.label ?? '');
                    }}
                  />
                  {errors.filterId && touched.filterId && (
                    <div className="error">{errors.filterId}</div>
                  )}
                </div>
              </div>
              <div className="form-row">
                <label htmlFor="mediaEligibilityDays" className="text-label">
                  {intl.formatMessage(messages.mediaEligibilityDays)}
                  <span className="label-tip">
                    {intl.formatMessage(messages.mediaEligibilityHelp)}
                  </span>
                </label>
                <div className="form-input-area">
                  <div className="form-input-field">
                    <Field
                      type="text"
                      inputMode="numeric"
                      id="mediaEligibilityDays"
                      name="mediaEligibilityDays"
                      className="short"
                    />
                  </div>
                  {errors.mediaEligibilityDays &&
                    touched.mediaEligibilityDays && (
                      <div className="error">{errors.mediaEligibilityDays}</div>
                    )}
                </div>
              </div>
              <div className="form-row">
                <label htmlFor="freshVisibilityDays" className="text-label">
                  {intl.formatMessage(messages.freshVisibilityDays)}
                  <span className="label-tip">
                    {intl.formatMessage(messages.freshVisibilityHelp)}
                  </span>
                </label>
                <div className="form-input-area">
                  <div className="form-input-field">
                    <Field
                      type="text"
                      inputMode="numeric"
                      id="freshVisibilityDays"
                      name="freshVisibilityDays"
                      className="short"
                    />
                  </div>
                  {errors.freshVisibilityDays &&
                    touched.freshVisibilityDays && (
                      <div className="error">{errors.freshVisibilityDays}</div>
                    )}
                </div>
              </div>
              <FreshContentFilters />
              <div className="actions">
                <div className="flex justify-end">
                  <Button
                    buttonType="primary"
                    type="submit"
                    disabled={isSubmitting || !isValid}
                  >
                    {isSubmitting && <ArrowPathIcon className="animate-spin" />}
                    {intl.formatMessage(messages.save)}
                  </Button>
                </div>
              </div>
            </Form>
          );
        }}
      </Formik>
      <div className="mt-12 border-t border-gray-700 pt-8">
        <h3 className="heading">{intl.formatMessage(messages.maintenance)}</h3>
        <p className="description">
          {intl.formatMessage(messages.maintenanceHelp)}
        </p>
        <Button
          buttonType="danger"
          disabled={rebuilding || refreshing || !data.enabled}
          onClick={() => setShowRebuildConfirmation(true)}
        >
          {rebuilding && <ArrowPathIcon className="animate-spin" />}
          <span>{intl.formatMessage(messages.rebuild)}</span>
        </Button>
      </div>
      <div className="mt-12">
        <div className="mb-4 flex items-center justify-between">
          <div>
            <h3 className="heading">
              {intl.formatMessage(messages.diagnostics)}
            </h3>
            <p className="description">
              {intl.formatMessage(messages.latestAttempt)}:{' '}
              {diagnostics?.latestAttempt?.outcome ?? '—'} ·{' '}
              {intl.formatMessage(messages.currentProjection)}:{' '}
              {diagnostics?.currentProjection.status ?? '—'} (
              {diagnostics?.currentProjection.itemCount ?? 0})
            </p>
            {diagnostics?.latestAttempt?.failingStage &&
              diagnostics.latestAttempt.failureReason && (
                <p className="mt-1 text-sm text-red-400">
                  {intl.formatMessage(messages.failedAt, {
                    stage: diagnosticLabel(
                      diagnostics.latestAttempt.failingStage
                    ),
                    reason: diagnosticLabel(
                      diagnostics.latestAttempt.failureReason
                    ),
                  })}
                </p>
              )}
            {['failed', 'cancelled'].includes(
              diagnostics?.latestAttempt?.outcome ?? ''
            ) && (
              <p className="mt-1 text-sm text-gray-300">
                {diagnostics?.latestAttempt?.lastGood
                  ? intl.formatMessage(messages.retainedProjection, {
                      timestamp: diagnostics.latestAttempt.lastGood.timestamp,
                      count: diagnostics.latestAttempt.lastGood.itemCount,
                    })
                  : intl.formatMessage(messages.noProjection)}
              </p>
            )}
          </div>
          <Button
            disabled={refreshing || rebuilding || !data.enabled}
            onClick={async () => {
              setRefreshing(true);
              try {
                const response = await axios.post<{ status: string }>(
                  '/api/v1/settings/fresh/refresh'
                );
                await Promise.all([
                  revalidateDiagnostics(),
                  mutate('/api/v1/fresh'),
                ]);
                if (['stale', 'unavailable'].includes(response.data.status)) {
                  addToast(
                    intl.formatMessage(
                      response.data.status === 'unavailable'
                        ? messages.refreshFailedNoProjection
                        : messages.refreshFailed
                    ),
                    {
                      appearance: 'error',
                      autoDismiss: true,
                    }
                  );
                } else {
                  addToast(intl.formatMessage(messages.refreshSuccess), {
                    appearance: 'success',
                    autoDismiss: true,
                  });
                }
              } catch {
                addToast(
                  intl.formatMessage(
                    diagnostics?.currentProjection.lastRefresh
                      ? messages.refreshFailed
                      : messages.refreshFailedNoProjection
                  ),
                  {
                    appearance: 'error',
                    autoDismiss: true,
                  }
                );
                await revalidateDiagnostics();
              } finally {
                setRefreshing(false);
              }
            }}
          >
            <ArrowPathIcon className={refreshing ? 'animate-spin' : ''} />
            <span>{intl.formatMessage(messages.refresh)}</span>
          </Button>
        </div>
        {!data.enabled && (
          <p className="mb-4 text-sm text-gray-400">
            {intl.formatMessage(messages.refreshDisabled)}
          </p>
        )}
        <div className="mb-6 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">
          {projectionRows.map(([label, value]) => (
            <div className="rounded-md bg-gray-800 p-3" key={label.id}>
              <div className="text-sm text-gray-400">
                {intl.formatMessage(label)}
              </div>
              <div className="break-words text-lg font-semibold">{value}</div>
            </div>
          ))}
        </div>
        {!diagnostics?.latestAttempt ? (
          <p className="text-gray-400">
            {intl.formatMessage(messages.noDiagnostics)}
          </p>
        ) : (
          <>
            <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">
              {countRows.map(([label, value]) => (
                <div className="rounded-md bg-gray-800 p-3" key={label.id}>
                  <div className="text-sm text-gray-400">
                    {intl.formatMessage(label)}
                  </div>
                  <div className="text-2xl font-semibold">
                    {value === null ? '—' : value.toLocaleString()}
                  </div>
                </div>
              ))}
            </div>
            <h4 className="mb-3 mt-8 text-xl font-semibold">
              {intl.formatMessage(messages.stages)}
            </h4>
            <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">
              {Object.entries(diagnostics.latestAttempt.stages).map(
                ([stage, status]) => (
                  <div className="rounded-md bg-gray-800 p-3" key={stage}>
                    <div className="text-sm text-gray-400">
                      {diagnosticLabel(stage)}
                    </div>
                    <div className="font-semibold">
                      {diagnosticLabel(status)}
                    </div>
                  </div>
                )
              )}
            </div>
            {diagnostics.latestAttempt.decisions.length > 0 && (
              <>
                <h4 className="mb-3 mt-8 text-xl font-semibold">
                  {intl.formatMessage(messages.decisions)}
                </h4>
                <div className="overflow-x-auto">
                  <table className="w-full text-left text-sm">
                    <thead className="text-gray-400">
                      <tr>
                        <th>{intl.formatMessage(messages.mediaTitle)}</th>
                        <th>{intl.formatMessage(messages.type)}</th>
                        <th>{intl.formatMessage(messages.year)}</th>
                        <th>{intl.formatMessage(messages.gate)}</th>
                        <th>{intl.formatMessage(messages.outcome)}</th>
                        <th>{intl.formatMessage(messages.reason)}</th>
                        <th>{intl.formatMessage(messages.matched)}</th>
                      </tr>
                    </thead>
                    <tbody>
                      {diagnostics.latestAttempt.decisions.map(
                        (decision, index) => (
                          <tr
                            className="border-t border-gray-700"
                            key={`${decision.reason}-${index}`}
                          >
                            <td>{decision.title}</td>
                            <td>{decision.mediaType}</td>
                            <td>{decision.year ?? '—'}</td>
                            <td>{diagnosticLabel(decision.stage)}</td>
                            <td>{diagnosticLabel(decision.outcome)}</td>
                            <td>{diagnosticLabel(decision.reason)}</td>
                            <td>
                              {decision.tmdbId
                                ? `${decision.mediaType}:${decision.tmdbId}`
                                : '—'}
                            </td>
                          </tr>
                        )
                      )}
                    </tbody>
                  </table>
                </div>
              </>
            )}
          </>
        )}
      </div>
      <CandidateDiagnostics
        key={diagnostics?.currentProjection.lastRefresh ?? 'uninitialized'}
      />
    </>
  );
};
export default SettingsFresh;
