@{
    BaseBranch = 'main'
    OriginRemote = 'origin'
    UpstreamRemote = 'upstream'
    ExpectedOriginRepositories = @('constbogdan/Mosaic')
    ExpectedUpstreamRepositories = @('damontecres/Wholphin')
    ValidationScript = 'scripts/validate-local.ps1'
    PullRequestTemplate = '.github/pull_request_template.md'
    UpstreamSyncBranchPattern = 'chore/sync-upstream-*'
    AutoMergeMethod = 'merge'

    HighRiskPatterns = @(
        '.gitignore'
        '.github/pull_request_template.md'
        '.github/workflows/*'
        '.github/actions/*'
        'app/build.gradle.kts'
        'build.gradle.kts'
        'settings.gradle.kts'
        'gradle/*'
        'gradle.properties'
        'app/src/*/AndroidManifest.xml'
        'app/src/main/proto/*'
        'app/src/main/java/*/AppPreference.kt'
        'app/src/main/java/*/AppPreferencesSerializer.kt'
        'app/src/main/java/*/services/*'
        'app/src/main/java/*/ui/nav/*'
        'app/schemas/*'
        'scripts/validate-local.ps1'
        'scripts/mosaic_validation_policy.py'
        'scripts/mosaic_output.ps1'
        'scripts/sync-upstream.ps1'
        'scripts/prepare-pr.ps1'
        'scripts/prepare-pr.config.psd1'
        'docs/AGENTS.md'
        'docs/UPSTREAM_SYNC.md'
        'docs/CODEX_HANDOFF.md'
        'docs/MOSAIC_ROADMAP.md'
        'docs/ARCHITECTURE.md'
        'docs/MOSAIC_IDENTITY.md'
    )

    RefusedArtifactPatterns = @(
        'validation.log'
        '*.apk'
        '*.aab'
        '*.jks'
        '*.keystore'
        '*.key'
        '*.p12'
        '*.pfx'
        'local.properties'
        '.env'
        '.env.*'
        'credentials.json'
        'secrets.properties'
        '.idea/*'
        '.vscode/*'
        '.gradle/*'
        'build/*'
        'app/build/*'
        '*~'
        '*.tmp'
        '*.swp'
    )
}
