@{
    BaseBranch = 'downstream-main'
    OriginRemote = 'origin'
    UpstreamRemote = 'upstream'
    UpstreamBranch = 'develop'
    ExpectedOriginRepositories = @('constbogdan/seerr')
    ExpectedUpstreamRepositories = @('seerr-team/seerr')
    ValidationScript = 'scripts/validate-local.ps1'
    PullRequestTemplate = '.github/PULL_REQUEST_TEMPLATE.md'
    UpstreamSyncBranchPattern = 'chore/sync-upstream-*'
    AutoMergeMethod = 'merge'

    HighRiskPatterns = @(
        '.gitignore'
        '.github/PULL_REQUEST_TEMPLATE.md'
        '.github/workflows/*'
        '.github/actions/*'
        'Dockerfile'
        'Dockerfile.local'
        'compose*.yaml'
        'charts/*'
        'package.json'
        'pnpm-lock.yaml'
        '.npmrc'
        'next.config.ts'
        'tsconfig.json'
        'seerr-api.yml'
        'server/api/*'
        'server/datasource.ts'
        'server/entity/*'
        'server/lib/settings/*'
        'server/middleware/*'
        'server/migration/*'
        'server/routes/*'
        'src/context/*'
        'src/hooks/*'
        'scripts/validate-local.ps1'
        'scripts/seerr_validation_policy.py'
        'scripts/seerr_change_classification.py'
        'scripts/seerr_repository.py'
        'scripts/seerr_validation_reuse.py'
        'scripts/hosted_upstream.py'
        'scripts/resolve_upstream.py'
        'scripts/resolve-upstream.ps1'
        'scripts/sync-upstream.ps1'
        'scripts/prepare-pr.ps1'
        'scripts/seerr_output.ps1'
        'scripts/prepare-pr.config.psd1'
        'scripts/upstream_ownership_policy.json'
        'scripts/seerr_downstream_version.py'
        'docs/PREPARE_PR.md'
        'docs/UPSTREAM_SYNC.md'
        'docs/UPSTREAM_RESOLUTION_DECISIONS.md'
        'docs/VALIDATION.md'
        'docs/downstream-workflow-inventory.txt'
        'docs/SEERR_DOWNSTREAM_MAINTENANCE.md'
        'docs/SEERR_DOWNSTREAM_PACKAGE.md'
        'docs/SEERR_DOWNSTREAM_ROADMAP.md'
        'docs/SEERR_HANDOFF.md'
    )

    RefusedArtifactPatterns = @(
        'validation.log'
        '*.jks'
        '*.keystore'
        '*.key'
        '*.p12'
        '*.pfx'
        '.env'
        '.env.*'
        'credentials.json'
        'secrets.properties'
        'config/*'
        '.idea/*'
        '.vscode/*'
        '.next/*'
        'dist/*'
        'node_modules/*'
        'coverage/*'
        'logs/*'
        '*.log'
        '*.db'
        '*.sqlite'
        '*.sqlite3'
        '.eslintcache'
        'tsconfig.tsbuildinfo'
        'pnpm-debug.log*'
        'npm-debug.log*'
        '*~'
        '*.tmp'
        '*.swp'
    )
}
